### PR TITLE
Fix suppression errors problems on Windows

### LINKED ISSUE #78: Suppressed errors still shows up as errors
**Describe the bug**
Ran `npx elm-review suppression` to suppress an error. Following `npx elm-review` still reports the error

**SSCCE (Short Self-Contained Correct Example)**
https://github.com/molteber/elm-review-suppress-bug-example

1. Run `npx elm-review` and get an error
2. Suppress that error with `npx elm-review suppress`
3. Run `npx elm-review` again.
4. See the suppressed error still being reported

**Expected behavior**
If any errors are reported with `elm-review`, running `elm-review suppress` and then `elm-review` should not report any errors

**Additional context**
I have only tried suppressing a `NoUnused.Exports.rule` rule

### PR DESCRIPTION
**Pull request by jfmengels**
Fixes #78 

- Fixed the glob for finding the suppressed errors on Windows.
- Changed the suppressed errors JSON so that files are always formatted with Unix-like `/` instead of Windows `\`

@molteber Sorry for the delay on working on this. Can you try out whether this worked? You can do that by:
1. Cloning this repo
2. Checkout the `issue-78-suppressed-bug` branch
3. Run `<path to node-elm-review folder>/bin/elm-review` (with the different parameters that you need)

Thank you in advance!

### CODE REVIEW

**Comment by molteber** [comment]
Hi @jfmengels 
I'll see if I can give it a try tonight or Monday :D

I'll keep you posted!

**Comment by molteber** [comment]
Scratch that, I got some time now

```
I found no errors!

There are still 1 suppressed error to address.
```

Success! 🎉  @jfmengels

**Comment by jfmengels** [comment]
Awesome, thanks for trying it out! I'll release it today :+1:

**Comment by jfmengels** [comment]
Released in v2.7.4 :+1:

**Pull request merged**
