### PR TITLE
Put `ls-engines` in library mode

### PR DESCRIPTION
**Pull request by lishaduck**
_**Split off from:** #190_

### CODE REVIEW

**Comment by lishaduck** [comment]
This failing is good, it's catching that we now need #190.

**Comment by lishaduck** [comment]
Great, more fun! Something else must've dropped node 14- in the whole glob fiasco. Welp. Whadawedonow?

**Comment by jfmengels** [comment]
:man_facepalming: :face_exhaling:

**Comment by lishaduck** [comment]
Oh, just saw this! npm/npm-pick-manifest#33 fixes a longstanding bug in npm, so engines-based resolution is a thing, just like it should be. Therefore, we can revert all of these engines changes, and npm won't install the newer glob/jackspeak/etc. However, if we support node 14, then we support npm 6 (and 8 and 10), so... no 😢
The next time this happens though, it should be much less of an issue 🎉

**Comment by lishaduck** [comment]
I've fixed this locally, need to split the giant branch into reviewable PRs.

**Comment by lishaduck** [comment]
Note: I did fix this, but I don't want to push it till #256 gets merged b/c my branches are complicated enough as-it.

**Comment by jfmengels** [comment]
Superseded by https://github.com/jfmengels/node-elm-review/pull/274

**Pull request closed without merging**
