### PR TITLE
Set `esModuleInterop` to true

### PR DESCRIPTION
**Pull request by lishaduck**
I turned it off a while ago, but it should be on. It's `allowSyntheticDefaultImports` that should be off.

### CODE REVIEW

**Review by lishaduck — COMMENTED** [review]
Ok, ran the following the my terminal twice, no flakes at all: 

```bash
for ((i=1; i<=5; i++)); do
turbo --ui=stream --force=true jest
done
```

Makes me wonder if the flake is Linux exclusive. I know I reproed it locally a while ago, but I can't seem to anymore.

**Comment by jfmengels** [comment]
Hmm possible. I managed to recreate similar flakes locally (Linux Ubuntu).

**Comment by jfmengels** [comment]
I was only able to recreate it by having multiple terminals running `jest`. So maybe it's because two tests try to compile the same application at the same time? :thinking:

**Comment by lishaduck** [comment]
> I was only able to recreate it by having multiple terminals running `jest`. So maybe it's because two tests try to compile the same application at the same time? 🤔

Hmm, that'd explain #319, as `elm-pages` has a lot of race conditions (I hear it's a lot better nowadays, so maybe not).
However, Jest tests don't run in parallel, do they? Oh... e2e tests and jest tests run in parallel... I'll try reverting that :)

**Comment by lishaduck** [comment]
> I was only able to recreate it by having multiple terminals running `jest`. So maybe it's because two tests try to compile the same application at the same time? 🤔

I, too, can repro it locally like that.

**Comment by lishaduck** [comment]
Disappointing, but I guess I just means I need to find the time to do that refactor of options parsing that'll let us quit spawning processes.

**Comment by lishaduck** [comment]
@jfmengels, do you want me to file an issue for supporting concurrent `elm-review` runs?

**Comment by jfmengels** [comment]
Yeah, the namespace option was meant for that. Though it's also a shame to need that, as that means that a cache for the CLI would not get used by an editor and vice versa. If we could get rid of it that would actually be nice I think.

@lishaduck opening an issue would be great 👍

**Pull request merged**
