### PR TITLE
Replace shell scripts

### PR DESCRIPTION
**Pull request by lishaduck**
Begin working toward the goals in #176.

VERY WIP!!!

After all that work trying to fix the shell, I decided to just nuke it and get copilot to do a basic js rewrite, which exposed a bunch of bugs. This simplifies the code at a (likely) small speed decrease.

---

Eventually (not in this PR 🤞), I'd like to replace these with test cases in Jest; even more eventually, I'd like to quit spawning processes in Jest tests, which would allow us to mock the filesystem using `memfs` and go back to running stuff in parallel (and give a massive perf boost, tests have a lot of overhead right now).

### CODE REVIEW

**Review by lishaduck — COMMENTED** [review]
Something broke in the rebase, but I'm otherwise satisfied with this iteration, and it seems to fix CI. (Once I fix it the rebase, can you retrigger ci a few more times to double check, @jfmengels?)

**Comment by jfmengels** [comment]
This is a great step forward! Thank you @lishaduck :tada:

**Comment by jfmengels** [comment]
@lishaduck I think the `test-run-record` might be broken, as some snapshots now get deleted. Maybe it's related to GitHub rate limits (but it didn't cause files to be removed). I'll try again later tonight if I get the time.

**Comment by lishaduck** [comment]
> @lishaduck I think the `test-run-record` might be broken, as some snapshots now get deleted. Maybe it's related to GitHub rate limits (but it didn't cause files to be removed). I'll try again later tonight if I get the time.

Hm. Oh, yep. Added this to stop it from destroying my standing with gh while testing:
https://github.com/jfmengels/node-elm-review/blob/7520c6bbf44a3a9225b007c6d39186faeb17a58f/test/run.mjs#L453-L455
It should be `(!SUBCOMMAND || (...))`

**Pull request merged**
