### PR TITLE
Get tests passing again

### PR DESCRIPTION
**Pull request by Arkham**
Hey there, just checked out the repo and noticed these tests were failing. Maybe it could be part of the release script to re-record the snapshots?

### CODE REVIEW

**Comment by Arkham** [comment]
Oh build failed because of the github authentication problem (:

**Comment by jfmengels** [comment]
Thanks :)

**Comment by Arkham** [comment]
By the way, would you mind tagging this repo as `hacktoberfest`? so I can track my open source contributions this month :)

**Comment by jfmengels** [comment]
Oh yeah, definitely. Done :)

**Pull request merged**
