### PR TITLE
Improve Tests (fix ci, enable typesafety, better unix/posix stuff, etc)

### PR DESCRIPTION
**Pull request by lishaduck**
_**Depends on:** #196._
_**Split off from:** #196._

### CODE REVIEW

**Review by jfmengels — APPROVED** [review]
Looks good to me. Interesting "going overboard" commit :smile: 

Can you resolve the conflicts? Then I'll merge the PR :+1:

**Comment by lishaduck** [comment]
> Interesting "going overboard" commit 😄

Function currying! (sort of)

Sorry it took so long. Was scratching my head over why my local main wasn't syncing with jfmengels:main (had to sync them on the remote), then I had dinner.

**Comment by lishaduck** [comment]
Pingy ping :)
Rebased this one, @jfmengels

**Comment by lishaduck** [comment]
Here ya go!

**Comment by lishaduck** [comment]
@jfmengels, can you merge this? I fixed all the CI errors, some stuff slipped through #193.

**Comment by lishaduck** [comment]
@jfmengels, ping again :)
This is blocking me getting more work done here, so I'd like to land this/get a review soon.

If you're sick or work is busy or on vacation, or whatever, I can wait, this isn't that important.
I can see that you're not right online right now, so this probably won't get to you. If it does get to you, though, I finished the side project I was finishing before I circled back to `elm-review`, and I'd like to knock out #125 soon, but I'd prefer to wait for this to get merged first.
Thanks!

**Comment by jfmengels** [comment]
Hey @lishaduck, sorry for the delay! I simply missed your messages.

PS: I'm not on vacation, but will soon be (and without a laptop) for a week or two. I could probably still review and merge small-ish PRs, but expect limited responsiveness.

**Comment by lishaduck** [comment]
> Hey @lishaduck, sorry for the delay! I simply missed your messages.

It's fine :)

> PS: I'm not on vacation, but will soon be (and without a laptop) for a week or two. I could probably still review and merge small-ish PRs, but expect limited responsiveness.

Sounds good! School's started back up, so I probably won't be making many mega-prs.

**Pull request merged**
